version: "3"
services:
  client:
    image: node:12.16-stretch
    working_dir: /usr/yatzy/client
    ports:
    - "5001:5001"
    volumes:
    - ./:/usr/yatzy
    command: >
      sh -c "npm install &&
             npm run start"
  server:
    image: python:3-alpine
    working_dir: /usr/yatzy/server
    ports:
    - "5000:5000"
    volumes:
    - ./:/usr/yatzy
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 yatzy.py"
  redis:
    image: redis:5-alpine
