version: "3"
services:
  development:
    image: node:12.16-stretch
    working_dir: /usr/src/app
    environment:
    - HOST=0.0.0.0
    - PORT=8080
    ports:
    - "8080:8080"
    volumes:
    - ./:/usr/src/app
    command:
    - npm
    - run
    - dev
